name: aws-cli-v2 # you probably want to 'snapcraft register <name>'
base: core20 # the base snap is the execution environment for this snap
version: 2.2.11
# version: git # just for humans, typically '1.2+git' or '1.3.2'
# version-script: cat $SNAPCRAFT_STAGE/version
summary: aws-cli version 2 because Amazon is taking too long # 79 char long summary
description: |
  The AWS Command Line Interface (CLI) is a unified tool to manage your AWS services. With just one tool to download and configure, you can control multiple AWS services from the command line and automate them through scripts.
  The AWS CLI v2 offers several new features including improved installers, new configuration options such as AWS Single Sign-On (SSO), and various interactive features. 

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  aws:
    command: bin/aws
    completer: bin/aws_bash_completer

parts:
  aws:
    plugin: python
    requirements: [ "requirements.txt" ]
    source: .
    stage-packages:
      - groff-base
